#!/bin/sh -f
# *********************************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : run.sh
# Simulator   : Riviera-PRO Simulator
# Description : Script for compiling design source files, automatically generated by Aldec Tcl Store app 1.27
# Created on  : Tue Oct 05 12:56:49 CEST 2021
#
# usage: run.sh
#
# *********************************************************************************************
bin_path=$RIVIERA_PATH
export xv_cpt_lib_path="$VIVADO_PATH/data/simmodels/riviera/2020.10/lnx64/6.2.0/systemc/protected"
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep $bin_path/rungui -l simulation.log -do "do {all.do}"
