#############################################################################################
#
# File name : sim_top_simulate.do
# Created on: Tue Oct 05 12:56:57 CEST 2021
#
# Script automatically generated by Aldec Tcl Store app 1.27 for 'behavioral' simulation,
# in Vivado v2021.1 (64-bit) for Riviera-PRO simulator.
#
#############################################################################################
set GENERIC_PATH /sim_top/dut/design_1_i/processing_system7_0/QEMU_PATH_TO_SOCKET_G

set SIM_OPT "-ieee_nowarn -i 5000 -t 1ps -relax -novopt +notimingchecks +access +r +m+sim_top"



eval asim $SIM_OPT +access +r -L unisims_ver -L unimacro_ver -L secureip -L xpm \
-L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_10 -L processing_system7_vip_v1_0_12 \
-L xil_defaultlib -L axi_lite_ipif_v3_0_4 -L lib_cdc_v1_0_2 -L interrupt_control_v3_1_4 \
-L axi_gpio_v2_0_26 -L generic_baseblocks_v2_1_0 -L axi_register_slice_v2_1_24 \
-L fifo_generator_v13_2_5 -L axi_data_fifo_v2_1_23 -L axi_crossbar_v2_1_25 \
-L axi_protocol_converter_v2_1_24 -L proc_sys_reset_v5_0_13 -L xilinx_vip \
-O5 xil_defaultlib.sim_top xil_defaultlib.glbl \
-g$GENERIC_PATH=$env(RPORT_PATH_HDL)

wave *



run -all


